apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: il9csemr5-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/il9csemr5-java-springboot-gitops